name = "img"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "LINK", id = "7cf78afe01b9471f925d76de765d332f",preview_id='7cf78afe01b9471f925d76de765d332f'}
]
[site]
bucket = "./static/dist"
